Ub fix bandersnatch provider
AFCYBER-DREAM/bashellite-providers pull request #7
Opened 2018-09-17 02:12 UTC by pcseanmckay

Updated bandersnatch provider to better parse the provider.conf config file.

2018-09-18 14:00 UTC, codrcodz requested changes
Same feedback as #6 

- Avoid calling external binaries when provisions already exist in bash for the thing you are trying to do
- Should we use sed instead of appending to the end of the file, or does location of not matter? What happens if two lines for the same parameter get dropped in the same file? does it accept the final one?

2018-09-19 05:49 UTC, pcseanmckay commented
See my relevant comments in PR #6.  Once again if you agree, then I will make the necessary changes.

2018-09-24 13:08 UTC, codrcodz commented on providers.d/bandersnatch/provider_wrapper.sh
> +    line_counter=$(($line_counter + 1))
This line needs to be inside the while loop near your `echo "directory` line. Right now, if the first line in the config file is something besides `^directory =`, your line_counter variable will get incremented, and your line_counter test will always hit your `else` conditional for each subsequent line.

2018-09-24 13:09 UTC, codrcodz requested changes
Correct logic issue.

2018-09-24 16:14 UTC, codrcodz approved these changes

2018-09-24 16:15 UTC, merged